language: python
dist: xenial
services:
  - xvfb
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
before_script:
  # Start a fake x server so that matplotlib doesn't fail
  - sudo apt-get install python-numpy python-scipy latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
script:
  - xvfb-run ./test.sh
cache: pip
